### PR TITLE
Create Cock Cock Hero - Island AI Upscale 2022.funscript

### PR DESCRIPTION
**Pull request by msstar449**
Sorry i make scripts for Cock hero Guilty dance pleasure and   but i dont know how correctly upload this in this master Cock hero FredTungsten with many cock hero scripts :(

### CODE REVIEW

**Comment by FredTungsten** [comment]
Looks like you created the script as a textfile online which kind of messed up the filename.

Easiest way to use GitHub imho is with [GitHub Desktop](https://desktop.github.com/)
It comes with a minimalistic UI and is [well documented](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/working-with-your-remote-repository-on-github-or-github-enterprise/creating-an-issue-or-pull-request)

**Comment by msstar449** [comment]
Thanks for answer. Sorry im really not good with english. ll try to put it together somehow using that program and deleted this broken contribution.

**Comment by FredTungsten** [comment]
👍

**Comment by msstar449** [comment]
I have other scripts in my master directory. I just need find way how this remove and insert this into Script Directory. If i understood, then there should be a possibility to merge these  Scripts directories. I think msstar449/Scripts with FredTungsten/Sripts. Just give me time and maybe I can do it. :D

**Comment by FredTungsten** [comment]
Sure. If it's a lot of scripts, you might want to put them into a separate directory (e.g. /msstar) with your own readme.md so people know you made them

**Comment by msstar449** [comment]
I thought I'd add them to that main script directory for better clarity. Or all those scripts are your job ?

**Comment by FredTungsten** [comment]
Yes, except for one script I made all of them

**Comment by msstar449** [comment]
Holy Moly !! I bow to the master. Thank you for such a portion of fun. In that case, the question is whether you want my poor scripts in your collection. After all, there will definitely be a difference in quality work. 
   But I'm a little confused. Where are the other people's scripts? Or you're the only one script creator ?

**Comment by msstar449** [comment]
Holy Moly !! I bow to the master. Thank you for such a portion of fun. In that case, the question is whether you want my poor scripts in your collection. After all, there will definitely be a difference in quality work. But I'm a little confused. Where are the other people's scripts? Or you're the only one script creator ?

**Comment by FredTungsten** [comment]
Thanks, but there are of course others too 😉 
Most of them can be found on [eroscripts.com](https://discuss.eroscripts.com/) these days.

If you plan on making more scripts of your own it would definitely make sense to start your own repository. I thought you only wanted to publish the one you had.

**Pull request merged**
